### ISSUE TITLE
Fail to create a guest account on OVE 4.7R1

### ISSUE THREAD

**Issue by ebcoelho** [BennyE/omniportal#9]
SSLError
requests.exceptions.SSLError: HTTPSConnectionPool(host='ov2500.lettel.com.br', port=443): Max retries exceeded with url: /sponsor/api/ham/guest/manager/judge (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

Traceback (most recent call last)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
return self.sslsocket_class._create(
File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
self.do_handshake()
File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
self._sslobj.do_handshake()
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/Users/eduardo/Downloads/iCloud Drive (Backup)/Documents/Python/omniportal/omniportal.py", line 210, in wrapped_view
return view(**kwargs)
File "/Users/eduardo/Downloads/iCloud Drive (Backup)/Documents/Python/omniportal/omniportal.py", line 1420, in add_guest
quick_guest_account(30)
File "/Users/eduardo/Downloads/iCloud Drive (Backup)/Documents/Python/omniportal/omniportal.py", line 967, in quick_guest_account
resp_login = req.post(f"{settings['guest_operator_url']}/sponsor/api/ham/guest/manager/judge", headers=login_header, json=login_data)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
return self.request("POST", url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='ov2500.lettel.com.br', port=443): Max retries exceeded with url: /sponsor/api/ham/guest/manager/judge (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))) 
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by BennyE** [comment]
Hi @ebcoelho,

OmniPortal uses the "Guest Operator" account through the "Guest Operator Portal".

For this to work, you need to
1. Create a Guest Operator Account in OmniVista 2500 via this menu https://ov2500.lettel.com.br/#/guest/guest-manager (screenshot below)
2. The https://ov2500-upam-cportal.al-enterprise.com/ **_in your DNS_** needs to resolve to your OmniVista UPAM Portal IP address, you can find the IP from your OmniVista Dashboard

**Guest Operator**
![ov-guest-operator](https://user-images.githubusercontent.com/5174414/209123151-9818580a-6260-46ab-a1e6-de44136e0c2d.png)

**DNS resolution of ov2500-upam-cportal.al-enterprise.com**
![ov-upam-nslookup](https://user-images.githubusercontent.com/5174414/209124180-9d1527fd-a6ac-40e1-abde-a5a2217e2c81.png)

Hope this helps! Have a good day!

Benny

**Comment by ebcoelho** [comment]
Hello Benny,

Updated UPAM settings but still not working.....I'm able to login on upam portal over https

![image](https://user-images.githubusercontent.com/16887421/209149137-51a0aeec-d05d-4291-a890-8c6a54e0a2c0.png)


On browser returned the messages below:

SSLError
requests.exceptions.SSLError: HTTPSConnectionPool(host='upam.lettel.com.br', port=443): Max retries exceeded with url: /sponsor/api/ham/guest/manager/judge (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

Traceback (most recent call last)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
return self.sslsocket_class._create(
File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
self.do_handshake()
File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
self._sslobj.do_handshake()
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/Users/eduardo/Downloads/iCloud Drive (Backup)/Documents/Python/omniportal/omniportal.py", line 210, in wrapped_view
return view(**kwargs)
File "/Users/eduardo/Downloads/iCloud Drive (Backup)/Documents/Python/omniportal/omniportal.py", line 1410, in add_guest
quick_guest_account(1)
File "/Users/eduardo/Downloads/iCloud Drive (Backup)/Documents/Python/omniportal/omniportal.py", line 967, in quick_guest_account
resp_login = req.post(f"{settings['guest_operator_url']}/sponsor/api/ham/guest/manager/judge", headers=login_header, json=login_data)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
return self.request("POST", url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='upam.lettel.com.br', port=443): Max retries exceeded with url: /sponsor/api/ham/guest/manager/judge (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))) 
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

on console the error messages below:

eduardo@Eduardos-MacBook-Pro omniportal % python3 -m flask --app omniportal --debug run --host 0.0.0.0 --port 5000
 * Serving Flask app 'omniportal'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.120:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 330-675-602
127.0.0.1 - - [22/Dec/2022 10:51:52] "GET /add_guest HTTP/1.1" 200 -
127.0.0.1 - - [22/Dec/2022 10:51:52] "GET /bootstrap/static/css/bootstrap.min.css HTTP/1.1" 304 -
127.0.0.1 - - [22/Dec/2022 10:51:52] "GET /bootstrap/static/icons/bootstrap-icons.svg HTTP/1.1" 304 -
127.0.0.1 - - [22/Dec/2022 10:51:52] "GET /bootstrap/static/umd/popper.min.js HTTP/1.1" 304 -
127.0.0.1 - - [22/Dec/2022 10:51:52] "GET /bootstrap/static/js/bootstrap.min.js HTTP/1.1" 304 -
127.0.0.1 - - [22/Dec/2022 10:51:58] "POST /add_guest HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='upam.lettel.com.br', port=443): Max retries exceeded with url: /sponsor/api/ham/guest/manager/judge (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/eduardo/Downloads/iCloud Drive (Backup)/Documents/Python/omniportal/omniportal.py", line 210, in wrapped_view
    return view(**kwargs)
  File "/Users/eduardo/Downloads/iCloud Drive (Backup)/Documents/Python/omniportal/omniportal.py", line 1410, in add_guest
    quick_guest_account(1)
  File "/Users/eduardo/Downloads/iCloud Drive (Backup)/Documents/Python/omniportal/omniportal.py", line 967, in quick_guest_account
    resp_login = req.post(f"{settings['guest_operator_url']}/sponsor/api/ham/guest/manager/judge", headers=login_header, json=login_data)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='upam.lettel.com.br', port=443): Max retries exceeded with url: /sponsor/api/ham/guest/manager/judge (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
127.0.0.1 - - [22/Dec/2022 10:51:58] "GET /add_guest?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [22/Dec/2022 10:51:58] "GET /add_guest?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [22/Dec/2022 10:51:58] "GET /add_guest?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -

**Comment by BennyE** [comment]
Hi @ebcoelho,

The access **has** to go through https://ov2500-upam-cportal.al-enterprise.com/, as I indicated in my post earlier. The reason for that is, that OmniVista 2500 Virtual Appliance and OmniVista Cirrus have a valid TLS certificate for that FQDN. The configuration should look like in the following screenshot. If you don't have a DNS server in your network that you can configure, you should be able to adapt your /etc/hosts file in Linux-like OS or %windir%\system32\drivers\etc\hosts (as you are on Windows)

Assuming that the IP address of your https://upam.lettel.com.br would be 192.168.2.16, the entry would look like this:
```
192.168.2.16 ov2500-upam-cportal.al-enterprise.com
```
![omniportal-config](https://user-images.githubusercontent.com/5174414/209150625-8737f506-5b56-4c81-bffc-9db336f52868.png)
